projects:
  whatisagame-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: 7bluqnonhfhufiz2majfr3c2ba
        maxDepth: 2
extensions:
  amplify:
    version: 3
